### ISSUE TITLE
What is linux equivalent of "host.docker.internal"

### ISSUE THREAD

**Issue by timowang1991** [timowang1991/docker-workshop#1]
On Macbook, we can use "host.docker.internal" as the hostname to connect back to the macbook loopback network, but we are unable to do the same on linux

**Comment by timowang1991** [comment]
on newer version of docker and docker-compose, we can do the followings.

----

for docker ([reference](https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal))
```bash
--add-host=host.docker.internal:host-gateway
```

----

for docker-compose ([reference](https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal/67158212#67158212) and [official docs](https://docs.docker.com/compose/compose-file/compose-file-v3/#extra_hosts))
```yaml
version: '3.7'

services:

  fpm:
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
```
